### ISSUE TITLE
cocoaPods的方式安装不了

### ISSUE THREAD

**Issue by mydy1987** [baidubce/bce-player-ios#1]
Resolving dependencies of `Podfile`
[!] Unable to find a specification for `BaiduBCEPlayerLSS (~> 1.0)`

在podfile中输入
pod 'BaiduBCEPlayerLSS', "~> 1.0" 会提示上面的错误，双引号换成单引号还是不行

**Comment by stayHF** [comment]
本地环境是可以的，有时间我找台Mac试一下。

**Comment by stayHF** [comment]
请先执行‘pod setup’ 
换了台Mac， 测试是没有问题的。
