### ISSUE TITLE
希望支持下载有METHOD=AES-128加密的M3U8格式，与 HLS 下载任务队列可以自定义

### ISSUE THREAD

**Issue by LeeCenY** [baidubce/bce-player-ios#4]
**下载前的M3U8格式是：**
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=AES-128,URI="**http://www.***.com/coursevideo-18571.html?key=94bdd4819ceb06382251fc1cd9fac478**"
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:17

**下载后的 M3U8文件格式是： 同一目录下保存密钥的 key.txt文件**
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=AES-128,URI="**key.txt"**
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:17

**Comment by stayHF** [comment]
您好！可以把联系方式发到我的邮箱吗？让我们的产品经理跟您沟通一下具体需求。

**Comment by LeeCenY** [comment]
已发，请查收

**Comment by LeeCenY** [comment]
@stayHF 已发，请查收

**Comment by stayHF** [comment]
产品经理如果跟您沟通过的话，可以把issue关闭。谢谢。

**Comment by asd8855** [comment]
iOS 播放器播放视频播放速度异常？直接在你们的Demo里播放是OK的？集成SDK是按照你们的文档一步一步做的     cbPlayerController = [[CyberPlayerController alloc]init];
    cbPlayerController.view.frame = CGRectMake(0, 64, 200, 200);
    [self.view addSubview:cbPlayerController.view];
    cbPlayerController.view.backgroundColor = [UIColor cyanColor];
    
//    self.ui_playerView.backgroundColor = [UIColor yellowColor];
    NSURL *url = [NSURL URLWithString:self.zlaMediaPlayerInfo.zlaSrc];
    //18d7ad8607a64bb5aa549c12bf39f322
    //ad24f173eb134bb0bcc8f06475d7fd8e
    NSString *msAK = @"18d7ad8607a64bb5aa549c12bf39f322";
    cbPlayerController.contentURL = url;
    [cbPlayerController setAccessKey:msAK];
    cbPlayerController.shouldAutoplay = YES;
    [cbPlayerController prepareToPlay];
