### ISSUE TITLE
希望Downloader可以增加普通视频譬如mp4等的支持

### ISSUE THREAD

**Issue by vinqon** [baidubce/bce-player-ios#5]
目前好像只能下载m3u8，给mp4地址会报错

**Comment by stayHF** [comment]
目前只支持m3u8格式，因为这种格式比较复杂，客户实现起来比较麻烦。
mp4格式这种单一文件的下载比较简单，可以先自己实现一下。
后续会评估一下是否支持mp4的下载，感谢支持。
