### ISSUE TITLE
建议拆分resume和uncompletedTask接口

### ISSUE THREAD

**Issue by vinqon** [baidubce/bce-player-ios#6]
```
/**
 *  @brief 继续上次未完成的下载任务。
 *  @return 返回下载任务的数组。
 */
- (NSArray<CyberDownloadTask*>*)resumeUncompletedTasks;
```

这个接口设计不符合单一原则啊，继续任务和获取任务做在一起，你让我想获取列表但是不想继续的人怎么办啊？

**Comment by vinqon** [comment]
把方法列表dump了出来，看到一个tasks的私有方法，目前就只能声明个category来调用解决了。

```
@interface CyberDownloader (private)

- (NSArray *)tasks;

@end
```

**Comment by qq756585379** [comment]
[cbPlayerController setCustomHttpHeader:[NSString stringWithFormat:@"Retry-After: 120\r\nCookie: %@\r\n",self.playM.com_cookie]];这是老版本方法。

新版本怎么不行
[bDCloudMediaPlayerController setOptionValue:str forKey:@"cookies" ofCategory:BDCloudMediaPlayerOptionCategoryFormat];
